- hosts: localhost
  connection: local
  become: true
  handlers:
    - include: 'handlers/main.yml'
  vars_files:
    - 'defaults/main.yml'
    - 'vars/main.yml'
  tasks:
    - include_tasks: 'tasks/main.yml'
